export const AL_SUBJECTS = {
    art: [
        'Arabic',
        'Art',
        'Bharatha Natayam',
        'Buddhism',
        'Buddhist Civilization',
        'Chinese',
        'Christian Civilization',
        'Christianity',
        'Communication and Media Studies',
        'Dance',
        'Economics',
        'English',
        'French',
        'Geography',
        'German',
        'Greek and Roman Civilization',
        'Hindi Language',
        'Hindu Civilization',
        'Hinduism',
        'History',
        'Home Economics',
        'Islam',
        'Islamic Civilization',
        'Japan Language',
        'Logic and Scientific Method',
        'Oriental Music',
        'Pali Language',
        'Political Science',
        'Russian',
        'Sanskrit',
        'Sinhala',
        'Tamil',
        'Western Music',
    ],
    maths: [
        'Chemistry',
        'Combine Mathematics',
        'Higher Mathematics',
        'Physics',
    ],
    bio: [
        'Agriculture',
        'Bio System Technology',
        'Biology',
        'Chemistry',
        'Physics',
        'Science for Technology',
    ],
    tech: [
        'Agro Technology',
        'Engineering Technology',
        'General Information Technology',
        'Information & Communication',
        'Technology',
    ],
    commerce: [
        'Accounting',
        'Business',
        'Statistics Business',
        'Studies Economics',
    ]
}