export const OL_SUBJECTS = [
    'Sinhala',
    'Tamil',
    'English',
    'Mathematics',
    'Science',
    'Religion',
    'Buddhism',
    'Catholicism',
    'Christianity',
    'Hinduism',
    'Islam',
    'History',
    'Business & Accounting Studies',
    'Geography',
    'Civic Education',
    'Entrepreneurship Studies',
    'Second Language - Sinhala',
    'Second Language - Tamil',
    'Eastern Music',
    'Western Music',
    'Carnatic Music',
    'Eastern Dancing',
    'Bharatha Dancing',
    'Art',
    'English Literature',
    'Sinhala Literature',
    'Tamil Literature',
    'Arabic Literature',
    'Drama and Theatre',
    'Information & Communication Technology',
    'Agriculture & Food Technology',
    'Aquatic Bio resources Technology',
    'Arts & Crafts',
    'Home Economics',
    'Health & Physical Education',
    'Communication & Media Studies',
    'Design & Construction Technology',
    'Design & Mechanical Technology',
    'Design, Electrical & Electronic Technology',
    'Electronic Writing & Shorthand',
]